---
- hosts: all
  sudo: yes
  vars:
      keyserver: hkp://keyserver.ubuntu.com:80
      keys: 36A1D7869245C8950F966E92D8576A8BA88D21E9
  tasks:
    - name: Add repository key
      shell: apt-key adv --keyserver {{keyserver}} --recv-keys {{keys}}

    - name: Setup repository
      apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present

    - name: Update packages
      apt: update_cache=yes

    - name: Upgrade
      apt: upgrade=safe

    - name: Install packages
      apt: pkg={{item}} state=latest
      with_items:
        - lxc-docker

    - name: Add vagrant user to docker group
      user: name=vagrant group=docker append=yes
